/**
 * Tactical marker library — traced from the AFP iSurv marker set (docx
 * export of their live map marker library), via a k-means colour
 * segmentation + potrace vectorisation pipeline (see ops session notes
 * for provenance and the pipeline script). Every icon here is a real
 * vector SVG, same as markerSvgs.ts's hand-drawn Surveillance shapes —
 * crisp at any zoom/device-pixel-ratio — rather than a small raster PNG,
 * which is what the very first 18-icon trial batch shipped as and the
 * reason those first 18 ever looked soft on a retina screen. Fixed-
 * colour, unlike the Surveillance set: an officer picks one as-is, no
 * colour swatch to apply.
 *
 * `group` sorts each icon into one of TACTICAL_GROUPS, approved
 * end-to-end against the full ~413-icon source library (574 raw entries
 * in the source doc, minus 161 that were just the same icon re-listed
 * under a second "CT Symbols\" or "Domestic Symbols\" category folder):
 * Target & Associates (4), Tactical (369 — team/callsign colour blocks,
 * cordon & control points, and the generic numbered markers, deliberately
 * one merged heading rather than three), Vehicles (16), Facilities (12,
 * including a handful of general points-of-interest that didn't fit any
 * other heading — Camera, Cell Tower, Coffee Cup, Container, Shopping
 * Centre, Toilets), Other Personnel (12).
 */

export type TacticalGroup =
  | "target_associates"
  | "tactical"
  | "vehicles"
  | "facilities"
  | "personnel";

export const TACTICAL_GROUPS: { key: TacticalGroup; label: string }[] = [
  { key: "target_associates", label: "Target & Associates" },
  { key: "tactical", label: "Tactical" },
  { key: "vehicles", label: "Vehicles" },
  { key: "facilities", label: "Facilities" },
  { key: "personnel", label: "Other Personnel" },
];

export interface TacticalIcon {
  key: string;
  label: string;
  src: string;
  group: TacticalGroup;
}

export const TACTICAL_ICONS: TacticalIcon[] = [
  {
    key: "a_red_1ae",
    label: "A_Red_1AE",
    src: "/tactical-markers/a_red_1ae.svg",
    group: "tactical",
  },
  {
    key: "a_red_1am",
    label: "A_Red_1AM",
    src: "/tactical-markers/a_red_1am.svg",
    group: "tactical",
  },
  {
    key: "a_red_1pe",
    label: "A_Red_1PE",
    src: "/tactical-markers/a_red_1pe.svg",
    group: "tactical",
  },
  {
    key: "a_red_1pm",
    label: "A_Red_1PM",
    src: "/tactical-markers/a_red_1pm.svg",
    group: "tactical",
  },
  {
    key: "a_red_aae",
    label: "A_Red_AAE",
    src: "/tactical-markers/a_red_aae.svg",
    group: "tactical",
  },
  {
    key: "a_red_aam",
    label: "A_Red_AAM",
    src: "/tactical-markers/a_red_aam.svg",
    group: "tactical",
  },
  {
    key: "a_red_ape",
    label: "A_Red_APE",
    src: "/tactical-markers/a_red_ape.svg",
    group: "tactical",
  },
  {
    key: "a_red_apm",
    label: "A_Red_APM",
    src: "/tactical-markers/a_red_apm.svg",
    group: "tactical",
  },
  {
    key: "aae",
    label: "AAE",
    src: "/tactical-markers/aae.svg",
    group: "tactical",
  },
  {
    key: "aam",
    label: "AAM",
    src: "/tactical-markers/aam.svg",
    group: "tactical",
  },
  {
    key: "afp",
    label: "AFP",
    src: "/tactical-markers/afp.svg",
    group: "tactical",
  },
  {
    key: "amarok",
    label: "AMAROK",
    src: "/tactical-markers/amarok.svg",
    group: "vehicles",
  },
  {
    key: "ambulance",
    label: "Ambulance",
    src: "/tactical-markers/ambulance.svg",
    group: "vehicles",
  },
  {
    key: "ape",
    label: "APE",
    src: "/tactical-markers/ape.svg",
    group: "tactical",
  },
  {
    key: "apm",
    label: "APM",
    src: "/tactical-markers/apm.svg",
    group: "tactical",
  },
  {
    key: "armoured_vehicle",
    label: "Armoured Vehicle",
    src: "/tactical-markers/armoured_vehicle.svg",
    group: "vehicles",
  },
  {
    key: "as",
    label: "AS",
    src: "/tactical-markers/as.svg",
    group: "tactical",
  },
  {
    key: "associate_address",
    label: "Associate Address",
    src: "/tactical-markers/associate_address.svg",
    group: "target_associates",
  },
  {
    key: "associate_vehicle",
    label: "Associate Vehicle",
    src: "/tactical-markers/associate_vehicle.svg",
    group: "target_associates",
  },
  {
    key: "australian_federal_police",
    label: "Australian Federal Police",
    src: "/tactical-markers/australian_federal_police.svg",
    group: "tactical",
  },
  {
    key: "b_blue_2ae",
    label: "B_Blue_2AE",
    src: "/tactical-markers/b_blue_2ae.svg",
    group: "tactical",
  },
  {
    key: "b_blue_2am",
    label: "B_Blue_2AM",
    src: "/tactical-markers/b_blue_2am.svg",
    group: "tactical",
  },
  {
    key: "b_blue_2pe",
    label: "B_Blue_2PE",
    src: "/tactical-markers/b_blue_2pe.svg",
    group: "tactical",
  },
  {
    key: "b_blue_2pm",
    label: "B_Blue_2PM",
    src: "/tactical-markers/b_blue_2pm.svg",
    group: "tactical",
  },
  {
    key: "b_blue_bae",
    label: "B_Blue_BAE",
    src: "/tactical-markers/b_blue_bae.svg",
    group: "tactical",
  },
  {
    key: "b_blue_bam",
    label: "B_Blue_BAM",
    src: "/tactical-markers/b_blue_bam.svg",
    group: "tactical",
  },
  {
    key: "b_blue_bpe",
    label: "B_Blue_BPE",
    src: "/tactical-markers/b_blue_bpe.svg",
    group: "tactical",
  },
  {
    key: "b_blue_bpm",
    label: "B_Blue_BPM",
    src: "/tactical-markers/b_blue_bpm.svg",
    group: "tactical",
  },
  {
    key: "bae",
    label: "BAE",
    src: "/tactical-markers/bae.svg",
    group: "tactical",
  },
  {
    key: "bam",
    label: "BAM",
    src: "/tactical-markers/bam.svg",
    group: "tactical",
  },
  {
    key: "bearcat",
    label: "BEARCAT",
    src: "/tactical-markers/bearcat.svg",
    group: "vehicles",
  },
  {
    key: "black_4wd",
    label: "BLACK 4WD",
    src: "/tactical-markers/black_4wd.svg",
    group: "vehicles",
  },
  {
    key: "black_cutoff",
    label: "BLACK CUTOFF",
    src: "/tactical-markers/black_cutoff.svg",
    group: "tactical",
  },
  {
    key: "black_side",
    label: "BLACK SIDE",
    src: "/tactical-markers/black_side.svg",
    group: "tactical",
  },
  {
    key: "bpe",
    label: "BPE",
    src: "/tactical-markers/bpe.svg",
    group: "tactical",
  },
  {
    key: "bpm",
    label: "BPM",
    src: "/tactical-markers/bpm.svg",
    group: "tactical",
  },
  {
    key: "c_green_3ae",
    label: "C_Green_3AE",
    src: "/tactical-markers/c_green_3ae.svg",
    group: "tactical",
  },
  {
    key: "c_green_3am",
    label: "C_Green_3AM",
    src: "/tactical-markers/c_green_3am.svg",
    group: "tactical",
  },
  {
    key: "c_green_3pe",
    label: "C_Green_3PE",
    src: "/tactical-markers/c_green_3pe.svg",
    group: "tactical",
  },
  {
    key: "c_green_3pm",
    label: "C_Green_3PM",
    src: "/tactical-markers/c_green_3pm.svg",
    group: "tactical",
  },
  {
    key: "c_green_cae",
    label: "C_Green_CAE",
    src: "/tactical-markers/c_green_cae.svg",
    group: "tactical",
  },
  {
    key: "c_green_cam",
    label: "C_Green_CAM",
    src: "/tactical-markers/c_green_cam.svg",
    group: "tactical",
  },
  {
    key: "c_green_cpe",
    label: "C_Green_CPE",
    src: "/tactical-markers/c_green_cpe.svg",
    group: "tactical",
  },
  {
    key: "c_green_cpm",
    label: "C_Green_CPM",
    src: "/tactical-markers/c_green_cpm.svg",
    group: "tactical",
  },
  {
    key: "cae",
    label: "CAE",
    src: "/tactical-markers/cae.svg",
    group: "tactical",
  },
  {
    key: "cam",
    label: "CAM",
    src: "/tactical-markers/cam.svg",
    group: "tactical",
  },
  {
    key: "camera",
    label: "Camera",
    src: "/tactical-markers/camera.svg",
    group: "facilities",
  },
  {
    key: "cell_tower",
    label: "Cell Tower",
    src: "/tactical-markers/cell_tower.svg",
    group: "facilities",
  },
  {
    key: "cib",
    label: "CIB",
    src: "/tactical-markers/cib.svg",
    group: "tactical",
  },
  {
    key: "circle_1",
    label: "CIRCLE 1",
    src: "/tactical-markers/circle_1.svg",
    group: "tactical",
  },
  {
    key: "circle_2",
    label: "CIRCLE 2",
    src: "/tactical-markers/circle_2.svg",
    group: "tactical",
  },
  {
    key: "circle_3",
    label: "CIRCLE 3",
    src: "/tactical-markers/circle_3.svg",
    group: "tactical",
  },
  {
    key: "circle_4",
    label: "CIRCLE 4",
    src: "/tactical-markers/circle_4.svg",
    group: "tactical",
  },
  {
    key: "circle_5",
    label: "CIRCLE 5",
    src: "/tactical-markers/circle_5.svg",
    group: "tactical",
  },
  {
    key: "circle_6",
    label: "CIRCLE 6",
    src: "/tactical-markers/circle_6.svg",
    group: "tactical",
  },
  {
    key: "circle_7",
    label: "CIRCLE 7",
    src: "/tactical-markers/circle_7.svg",
    group: "tactical",
  },
  {
    key: "circle_8",
    label: "CIRCLE 8",
    src: "/tactical-markers/circle_8.svg",
    group: "tactical",
  },
  {
    key: "circle_9",
    label: "CIRCLE 9",
    src: "/tactical-markers/circle_9.svg",
    group: "tactical",
  },
  {
    key: "cleared_sh_or_area",
    label: "Cleared SH or Area",
    src: "/tactical-markers/cleared_sh_or_area.svg",
    group: "tactical",
  },
  {
    key: "close_personal_protection",
    label: "Close Personal Protection",
    src: "/tactical-markers/close_personal_protection.svg",
    group: "tactical",
  },
  {
    key: "coffee_cup",
    label: "Coffee Cup",
    src: "/tactical-markers/coffee_cup.svg",
    group: "facilities",
  },
  {
    key: "comd_post",
    label: "COMD POST",
    src: "/tactical-markers/comd_post.svg",
    group: "facilities",
  },
  {
    key: "container",
    label: "CONTAINER",
    src: "/tactical-markers/container.svg",
    group: "facilities",
  },
  {
    key: "cordon_inner",
    label: "Cordon Inner",
    src: "/tactical-markers/cordon_inner.svg",
    group: "tactical",
  },
  {
    key: "cordon_outer",
    label: "Cordon Outer",
    src: "/tactical-markers/cordon_outer.svg",
    group: "tactical",
  },
  {
    key: "covert_deployment_vehicle",
    label: "Covert Deployment Vehicle",
    src: "/tactical-markers/covert_deployment_vehicle.svg",
    group: "vehicles",
  },
  {
    key: "cpe",
    label: "CPE",
    src: "/tactical-markers/cpe.svg",
    group: "tactical",
  },
  {
    key: "cpm",
    label: "CPM",
    src: "/tactical-markers/cpm.svg",
    group: "tactical",
  },
  {
    key: "crp",
    label: "CRP",
    src: "/tactical-markers/crp.svg",
    group: "tactical",
  },
  {
    key: "cvt_veh",
    label: "CVT VEH",
    src: "/tactical-markers/cvt_veh.svg",
    group: "vehicles",
  },
  {
    key: "d_purple_4ae",
    label: "D_Purple_4AE",
    src: "/tactical-markers/d_purple_4ae.svg",
    group: "tactical",
  },
  {
    key: "d_purple_4am",
    label: "D_Purple_4AM",
    src: "/tactical-markers/d_purple_4am.svg",
    group: "tactical",
  },
  {
    key: "d_purple_4pe",
    label: "D_Purple_4PE",
    src: "/tactical-markers/d_purple_4pe.svg",
    group: "tactical",
  },
  {
    key: "d_purple_4pm",
    label: "D_Purple_4PM",
    src: "/tactical-markers/d_purple_4pm.svg",
    group: "tactical",
  },
  {
    key: "d_purple_dae",
    label: "D_Purple_DAE",
    src: "/tactical-markers/d_purple_dae.svg",
    group: "tactical",
  },
  {
    key: "d_purple_dam",
    label: "D_Purple_DAM",
    src: "/tactical-markers/d_purple_dam.svg",
    group: "tactical",
  },
  {
    key: "d_purple_dpe",
    label: "D_Purple_DPE",
    src: "/tactical-markers/d_purple_dpe.svg",
    group: "tactical",
  },
  {
    key: "d_purple_dpm",
    label: "D_Purple_DPM",
    src: "/tactical-markers/d_purple_dpm.svg",
    group: "tactical",
  },
  {
    key: "dae",
    label: "DAE",
    src: "/tactical-markers/dae.svg",
    group: "tactical",
  },
  {
    key: "dam",
    label: "DAM",
    src: "/tactical-markers/dam.svg",
    group: "tactical",
  },
  {
    key: "dir_sierra_1",
    label: "DIR SIERRA 1",
    src: "/tactical-markers/dir_sierra_1.svg",
    group: "tactical",
  },
  {
    key: "dir_sierra_2",
    label: "DIR SIERRA 2",
    src: "/tactical-markers/dir_sierra_2.svg",
    group: "tactical",
  },
  {
    key: "dir_sierra_3",
    label: "DIR SIERRA 3",
    src: "/tactical-markers/dir_sierra_3.svg",
    group: "tactical",
  },
  {
    key: "dir_sierra_4",
    label: "DIR SIERRA 4",
    src: "/tactical-markers/dir_sierra_4.svg",
    group: "tactical",
  },
  {
    key: "dir_sierra_5",
    label: "DIR SIERRA 5",
    src: "/tactical-markers/dir_sierra_5.svg",
    group: "tactical",
  },
  {
    key: "dir_sierra_6",
    label: "DIR SIERRA 6",
    src: "/tactical-markers/dir_sierra_6.svg",
    group: "tactical",
  },
  {
    key: "dir_sierra_7",
    label: "DIR SIERRA 7",
    src: "/tactical-markers/dir_sierra_7.svg",
    group: "tactical",
  },
  {
    key: "dir_sierra_8",
    label: "DIR SIERRA 8",
    src: "/tactical-markers/dir_sierra_8.svg",
    group: "tactical",
  },
  {
    key: "dir_sierra_9",
    label: "DIR SIERRA 9",
    src: "/tactical-markers/dir_sierra_9.svg",
    group: "tactical",
  },
  {
    key: "distraction",
    label: "Distraction",
    src: "/tactical-markers/distraction.svg",
    group: "tactical",
  },
  {
    key: "diversion",
    label: "DIVERSION",
    src: "/tactical-markers/diversion.svg",
    group: "tactical",
  },
  {
    key: "dog",
    label: "Dog",
    src: "/tactical-markers/dog.svg",
    group: "personnel",
  },
  {
    key: "dpe",
    label: "DPE",
    src: "/tactical-markers/dpe.svg",
    group: "tactical",
  },
  {
    key: "dpm",
    label: "DPM",
    src: "/tactical-markers/dpm.svg",
    group: "tactical",
  },
  {
    key: "e_yellow_5ae",
    label: "E_Yellow_5AE",
    src: "/tactical-markers/e_yellow_5ae.svg",
    group: "tactical",
  },
  {
    key: "e_yellow_5am",
    label: "E_Yellow_5AM",
    src: "/tactical-markers/e_yellow_5am.svg",
    group: "tactical",
  },
  {
    key: "e_yellow_5pe",
    label: "E_Yellow_5PE",
    src: "/tactical-markers/e_yellow_5pe.svg",
    group: "tactical",
  },
  {
    key: "e_yellow_5pm",
    label: "E_Yellow_5PM",
    src: "/tactical-markers/e_yellow_5pm.svg",
    group: "tactical",
  },
  {
    key: "e_yellow_eae",
    label: "E_Yellow_EAE",
    src: "/tactical-markers/e_yellow_eae.svg",
    group: "tactical",
  },
  {
    key: "e_yellow_eam",
    label: "E_Yellow_EAM",
    src: "/tactical-markers/e_yellow_eam.svg",
    group: "tactical",
  },
  {
    key: "e_yellow_epe",
    label: "E_Yellow_EPE",
    src: "/tactical-markers/e_yellow_epe.svg",
    group: "tactical",
  },
  {
    key: "e_yellow_epm",
    label: "E_Yellow_EPM",
    src: "/tactical-markers/e_yellow_epm.svg",
    group: "tactical",
  },
  {
    key: "ea_commander_rv",
    label: "EA Commander RV",
    src: "/tactical-markers/ea_commander_rv.svg",
    group: "tactical",
  },
  {
    key: "eacomdrv",
    label: "EACOMDRV",
    src: "/tactical-markers/eacomdrv.svg",
    group: "tactical",
  },
  {
    key: "eae",
    label: "EAE",
    src: "/tactical-markers/eae.svg",
    group: "tactical",
  },
  {
    key: "eam",
    label: "EAM",
    src: "/tactical-markers/eam.svg",
    group: "tactical",
  },
  {
    key: "east",
    label: "EAST",
    src: "/tactical-markers/east.svg",
    group: "tactical",
  },
  {
    key: "emergency_services",
    label: "Emergency Services",
    src: "/tactical-markers/emergency_services.svg",
    group: "tactical",
  },
  {
    key: "emergsvcs",
    label: "EMERGSVCS",
    src: "/tactical-markers/emergsvcs.svg",
    group: "tactical",
  },
  {
    key: "entry_point_alpha_alternate",
    label: "Entry Point Alpha Alternate",
    src: "/tactical-markers/entry_point_alpha_alternate.svg",
    group: "tactical",
  },
  {
    key: "entry_point_alpha_primary",
    label: "Entry Point Alpha Primary",
    src: "/tactical-markers/entry_point_alpha_primary.svg",
    group: "tactical",
  },
  {
    key: "entry_point_bravo_alternate",
    label: "Entry Point Bravo Alternate",
    src: "/tactical-markers/entry_point_bravo_alternate.svg",
    group: "tactical",
  },
  {
    key: "entry_point_bravo_primary",
    label: "Entry Point Bravo Primary",
    src: "/tactical-markers/entry_point_bravo_primary.svg",
    group: "tactical",
  },
  {
    key: "entry_point_charlie_alternate",
    label: "Entry Point Charlie Alternate",
    src: "/tactical-markers/entry_point_charlie_alternate.svg",
    group: "tactical",
  },
  {
    key: "entry_point_charlie_primary",
    label: "Entry Point Charlie Primary",
    src: "/tactical-markers/entry_point_charlie_primary.svg",
    group: "tactical",
  },
  {
    key: "entry_point_delta_alternate",
    label: "Entry Point Delta Alternate",
    src: "/tactical-markers/entry_point_delta_alternate.svg",
    group: "tactical",
  },
  {
    key: "entry_point_delta_primary",
    label: "Entry Point Delta Primary",
    src: "/tactical-markers/entry_point_delta_primary.svg",
    group: "tactical",
  },
  {
    key: "eort",
    label: "EORT",
    src: "/tactical-markers/eort.svg",
    group: "tactical",
  },
  {
    key: "epe",
    label: "EPE",
    src: "/tactical-markers/epe.svg",
    group: "tactical",
  },
  {
    key: "epm",
    label: "EPM",
    src: "/tactical-markers/epm.svg",
    group: "tactical",
  },
  {
    key: "eva",
    label: "EVA",
    src: "/tactical-markers/eva.svg",
    group: "tactical",
  },
  {
    key: "fae",
    label: "FAE",
    src: "/tactical-markers/fae.svg",
    group: "tactical",
  },
  {
    key: "fam",
    label: "FAM",
    src: "/tactical-markers/fam.svg",
    group: "tactical",
  },
  {
    key: "fap",
    label: "FAP",
    src: "/tactical-markers/fap.svg",
    group: "tactical",
  },
  {
    key: "fap_a",
    label: "FAP - A",
    src: "/tactical-markers/fap_a.svg",
    group: "tactical",
  },
  {
    key: "fap_b",
    label: "FAP - B",
    src: "/tactical-markers/fap_b.svg",
    group: "tactical",
  },
  {
    key: "fap_c",
    label: "FAP - C",
    src: "/tactical-markers/fap_c.svg",
    group: "tactical",
  },
  {
    key: "fap_d",
    label: "FAP - D",
    src: "/tactical-markers/fap_d.svg",
    group: "tactical",
  },
  {
    key: "fap_e",
    label: "FAP - E",
    src: "/tactical-markers/fap_e.svg",
    group: "tactical",
  },
  {
    key: "fap_g",
    label: "FAP - G",
    src: "/tactical-markers/fap_g.svg",
    group: "tactical",
  },
  {
    key: "fap_all_teams",
    label: "FAP All Teams",
    src: "/tactical-markers/fap_all_teams.svg",
    group: "tactical",
  },
  {
    key: "fap_alpha",
    label: "FAP Alpha",
    src: "/tactical-markers/fap_alpha.svg",
    group: "tactical",
  },
  {
    key: "fap_alpha_ot_team_1",
    label: "FAP Alpha  ot  Team 1",
    src: "/tactical-markers/fap_alpha_ot_team_1.svg",
    group: "tactical",
  },
  {
    key: "fap_bravo",
    label: "FAP Bravo",
    src: "/tactical-markers/fap_bravo.svg",
    group: "tactical",
  },
  {
    key: "fap_bravo_or_team_2",
    label: "FAP Bravo or Team 2",
    src: "/tactical-markers/fap_bravo_or_team_2.svg",
    group: "tactical",
  },
  {
    key: "fap_charlie",
    label: "FAP Charlie",
    src: "/tactical-markers/fap_charlie.svg",
    group: "tactical",
  },
  {
    key: "fap_charlie_or_team_3",
    label: "FAP Charlie or Team 3",
    src: "/tactical-markers/fap_charlie_or_team_3.svg",
    group: "tactical",
  },
  {
    key: "fap_delta",
    label: "FAP Delta",
    src: "/tactical-markers/fap_delta.svg",
    group: "tactical",
  },
  {
    key: "fap_delta_or_team_4",
    label: "FAP Delta or Team 4",
    src: "/tactical-markers/fap_delta_or_team_4.svg",
    group: "tactical",
  },
  {
    key: "fap_echo",
    label: "FAP Echo",
    src: "/tactical-markers/fap_echo.svg",
    group: "tactical",
  },
  {
    key: "fap_echo_or_team_5",
    label: "FAP Echo or Team 5",
    src: "/tactical-markers/fap_echo_or_team_5.svg",
    group: "tactical",
  },
  {
    key: "fap_golf",
    label: "FAP Golf",
    src: "/tactical-markers/fap_golf.svg",
    group: "tactical",
  },
  {
    key: "fap_golf_or_team_6",
    label: "FAP Golf or Team 6",
    src: "/tactical-markers/fap_golf_or_team_6.svg",
    group: "tactical",
  },
  {
    key: "fap_marksman",
    label: "FAP Marksman",
    src: "/tactical-markers/fap_marksman.svg",
    group: "tactical",
  },
  {
    key: "fire_truck",
    label: "Fire_Truck",
    src: "/tactical-markers/fire_truck.svg",
    group: "vehicles",
  },
  {
    key: "firm_base",
    label: "Firm Base",
    src: "/tactical-markers/firm_base.svg",
    group: "facilities",
  },
  {
    key: "foot_approach",
    label: "Foot Approach",
    src: "/tactical-markers/foot_approach.svg",
    group: "tactical",
  },
  {
    key: "foot_approach_alpha",
    label: "Foot Approach Alpha",
    src: "/tactical-markers/foot_approach_alpha.svg",
    group: "tactical",
  },
  {
    key: "foot_approach_bravo",
    label: "Foot Approach Bravo",
    src: "/tactical-markers/foot_approach_bravo.svg",
    group: "tactical",
  },
  {
    key: "foot_approach_charlie",
    label: "Foot Approach Charlie",
    src: "/tactical-markers/foot_approach_charlie.svg",
    group: "tactical",
  },
  {
    key: "foot_approach_delta",
    label: "Foot Approach Delta",
    src: "/tactical-markers/foot_approach_delta.svg",
    group: "tactical",
  },
  {
    key: "foot_approach_echo",
    label: "Foot Approach Echo",
    src: "/tactical-markers/foot_approach_echo.svg",
    group: "tactical",
  },
  {
    key: "foot_approach_golf",
    label: "Foot Approach Golf",
    src: "/tactical-markers/foot_approach_golf.svg",
    group: "tactical",
  },
  {
    key: "foot_approach_marksman",
    label: "Foot Approach Marksman",
    src: "/tactical-markers/foot_approach_marksman.svg",
    group: "tactical",
  },
  {
    key: "foot_team",
    label: "Foot Team",
    src: "/tactical-markers/foot_team.svg",
    group: "tactical",
  },
  {
    key: "foot_team_1",
    label: "Foot Team 1",
    src: "/tactical-markers/foot_team_1.svg",
    group: "tactical",
  },
  {
    key: "foot_team_2",
    label: "Foot Team 2",
    src: "/tactical-markers/foot_team_2.svg",
    group: "tactical",
  },
  {
    key: "foot_team_3",
    label: "Foot Team 3",
    src: "/tactical-markers/foot_team_3.svg",
    group: "tactical",
  },
  {
    key: "foot_team_4",
    label: "Foot Team 4",
    src: "/tactical-markers/foot_team_4.svg",
    group: "tactical",
  },
  {
    key: "foot_team_5",
    label: "Foot Team 5",
    src: "/tactical-markers/foot_team_5.svg",
    group: "tactical",
  },
  {
    key: "foot_team_6",
    label: "Foot Team 6",
    src: "/tactical-markers/foot_team_6.svg",
    group: "tactical",
  },
  {
    key: "foot_team_7",
    label: "Foot Team 7",
    src: "/tactical-markers/foot_team_7.svg",
    group: "tactical",
  },
  {
    key: "foot_team_8",
    label: "Foot Team 8",
    src: "/tactical-markers/foot_team_8.svg",
    group: "tactical",
  },
  {
    key: "foot_team_9",
    label: "Foot Team 9",
    src: "/tactical-markers/foot_team_9.svg",
    group: "tactical",
  },
  {
    key: "fpe",
    label: "FPE",
    src: "/tactical-markers/fpe.svg",
    group: "tactical",
  },
  {
    key: "fpm",
    label: "FPM",
    src: "/tactical-markers/fpm.svg",
    group: "tactical",
  },
  {
    key: "friendly_address",
    label: "Friendly Address",
    src: "/tactical-markers/friendly_address.svg",
    group: "tactical",
  },
  {
    key: "fup",
    label: "FUP",
    src: "/tactical-markers/fup.svg",
    group: "tactical",
  },
  {
    key: "fup_1",
    label: "FUP 1",
    src: "/tactical-markers/fup_1.svg",
    group: "tactical",
  },
  {
    key: "fup_2",
    label: "FUP 2",
    src: "/tactical-markers/fup_2.svg",
    group: "tactical",
  },
  {
    key: "fup_all_teams",
    label: "FUP All Teams",
    src: "/tactical-markers/fup_all_teams.svg",
    group: "tactical",
  },
  {
    key: "fup_alpha",
    label: "FUP Alpha",
    src: "/tactical-markers/fup_alpha.svg",
    group: "tactical",
  },
  {
    key: "fup_alpha_1",
    label: "FUP Alpha 1",
    src: "/tactical-markers/fup_alpha_1.svg",
    group: "tactical",
  },
  {
    key: "fup_alpha_2",
    label: "FUP Alpha 2",
    src: "/tactical-markers/fup_alpha_2.svg",
    group: "tactical",
  },
  {
    key: "fup_bravo",
    label: "FUP Bravo",
    src: "/tactical-markers/fup_bravo.svg",
    group: "tactical",
  },
  {
    key: "fup_bravo_1",
    label: "FUP Bravo 1",
    src: "/tactical-markers/fup_bravo_1.svg",
    group: "tactical",
  },
  {
    key: "fup_bravo_2",
    label: "FUP Bravo 2",
    src: "/tactical-markers/fup_bravo_2.svg",
    group: "tactical",
  },
  {
    key: "fup_charlie",
    label: "FUP Charlie",
    src: "/tactical-markers/fup_charlie.svg",
    group: "tactical",
  },
  {
    key: "fup_charlie_1",
    label: "FUP Charlie 1",
    src: "/tactical-markers/fup_charlie_1.svg",
    group: "tactical",
  },
  {
    key: "fup_charlie_2",
    label: "FUP Charlie 2",
    src: "/tactical-markers/fup_charlie_2.svg",
    group: "tactical",
  },
  {
    key: "fup_delta",
    label: "FUP Delta",
    src: "/tactical-markers/fup_delta.svg",
    group: "tactical",
  },
  {
    key: "fup_delta_1",
    label: "FUP Delta 1",
    src: "/tactical-markers/fup_delta_1.svg",
    group: "tactical",
  },
  {
    key: "fup_delta_2",
    label: "FUP Delta 2",
    src: "/tactical-markers/fup_delta_2.svg",
    group: "tactical",
  },
  {
    key: "fup_echo",
    label: "FUP Echo",
    src: "/tactical-markers/fup_echo.svg",
    group: "tactical",
  },
  {
    key: "fup_echo_1",
    label: "FUP Echo 1",
    src: "/tactical-markers/fup_echo_1.svg",
    group: "tactical",
  },
  {
    key: "fup_echo_2",
    label: "FUP Echo 2",
    src: "/tactical-markers/fup_echo_2.svg",
    group: "tactical",
  },
  {
    key: "fup_golf",
    label: "FUP Golf",
    src: "/tactical-markers/fup_golf.svg",
    group: "tactical",
  },
  {
    key: "fup_golf_1",
    label: "FUP Golf 1",
    src: "/tactical-markers/fup_golf_1.svg",
    group: "tactical",
  },
  {
    key: "fup_golf_2",
    label: "FUP Golf 2",
    src: "/tactical-markers/fup_golf_2.svg",
    group: "tactical",
  },
  {
    key: "fup_marksman",
    label: "FUP Marksman",
    src: "/tactical-markers/fup_marksman.svg",
    group: "tactical",
  },
  {
    key: "fup_marksman_1",
    label: "FUP Marksman 1",
    src: "/tactical-markers/fup_marksman_1.svg",
    group: "tactical",
  },
  {
    key: "fup_marksman_2",
    label: "FUP Marksman 2",
    src: "/tactical-markers/fup_marksman_2.svg",
    group: "tactical",
  },
  {
    key: "fwd_hold_area",
    label: "FWD HOLD AREA",
    src: "/tactical-markers/fwd_hold_area.svg",
    group: "tactical",
  },
  {
    key: "g_brown_7ae",
    label: "G_Brown_7AE",
    src: "/tactical-markers/g_brown_7ae.svg",
    group: "tactical",
  },
  {
    key: "g_brown_7am",
    label: "G_Brown_7AM",
    src: "/tactical-markers/g_brown_7am.svg",
    group: "tactical",
  },
  {
    key: "g_brown_7pe",
    label: "G_Brown_7PE",
    src: "/tactical-markers/g_brown_7pe.svg",
    group: "tactical",
  },
  {
    key: "g_brown_7pm",
    label: "G_Brown_7PM",
    src: "/tactical-markers/g_brown_7pm.svg",
    group: "tactical",
  },
  {
    key: "g_brown_gae",
    label: "G_Brown_GAE",
    src: "/tactical-markers/g_brown_gae.svg",
    group: "tactical",
  },
  {
    key: "g_brown_gam",
    label: "G_Brown_GAM",
    src: "/tactical-markers/g_brown_gam.svg",
    group: "tactical",
  },
  {
    key: "g_brown_gpe",
    label: "G_Brown_GPE",
    src: "/tactical-markers/g_brown_gpe.svg",
    group: "tactical",
  },
  {
    key: "g_brown_gpm",
    label: "G_Brown_GPM",
    src: "/tactical-markers/g_brown_gpm.svg",
    group: "tactical",
  },
  {
    key: "gae",
    label: "GAE",
    src: "/tactical-markers/gae.svg",
    group: "tactical",
  },
  {
    key: "gam",
    label: "GAM",
    src: "/tactical-markers/gam.svg",
    group: "tactical",
  },
  {
    key: "gen_duty",
    label: "GEN DUTY",
    src: "/tactical-markers/gen_duty.svg",
    group: "tactical",
  },
  {
    key: "general_duties",
    label: "General Duties",
    src: "/tactical-markers/general_duties.svg",
    group: "tactical",
  },
  {
    key: "gpe",
    label: "GPE",
    src: "/tactical-markers/gpe.svg",
    group: "tactical",
  },
  {
    key: "gpm",
    label: "GPM",
    src: "/tactical-markers/gpm.svg",
    group: "tactical",
  },
  {
    key: "green_cutoff",
    label: "GREEN CUTOFF",
    src: "/tactical-markers/green_cutoff.svg",
    group: "tactical",
  },
  {
    key: "green_side",
    label: "GREEN SIDE",
    src: "/tactical-markers/green_side.svg",
    group: "tactical",
  },
  {
    key: "helo_loit_loc",
    label: "HELO LOIT LOC",
    src: "/tactical-markers/helo_loit_loc.svg",
    group: "tactical",
  },
  {
    key: "helo_loitre_loc",
    label: "Helo  Loitre  Loc",
    src: "/tactical-markers/helo_loitre_loc.svg",
    group: "tactical",
  },
  {
    key: "helo_lp",
    label: "Helo LP",
    src: "/tactical-markers/helo_lp.svg",
    group: "tactical",
  },
  {
    key: "holdarea",
    label: "HOLDAREA",
    src: "/tactical-markers/holdarea.svg",
    group: "tactical",
  },
  {
    key: "holding_area",
    label: "Holding Area",
    src: "/tactical-markers/holding_area.svg",
    group: "tactical",
  },
  {
    key: "hospital",
    label: "Hospital",
    src: "/tactical-markers/hospital.svg",
    group: "facilities",
  },
  {
    key: "host",
    label: "HOST",
    src: "/tactical-markers/host.svg",
    group: "tactical",
  },
  {
    key: "hostage",
    label: "Hostage",
    src: "/tactical-markers/hostage.svg",
    group: "tactical",
  },
  {
    key: "hostage_reception_point_alternate",
    label: "Hostage Reception Point Alternate",
    src: "/tactical-markers/hostage_reception_point_alternate.svg",
    group: "tactical",
  },
  {
    key: "hostage_reception_point_primary",
    label: "Hostage Reception Point Primary",
    src: "/tactical-markers/hostage_reception_point_primary.svg",
    group: "tactical",
  },
  {
    key: "hostile_address",
    label: "Hostile Address",
    src: "/tactical-markers/hostile_address.svg",
    group: "tactical",
  },
  {
    key: "hra_alt",
    label: "HRA ALT",
    src: "/tactical-markers/hra_alt.svg",
    group: "tactical",
  },
  {
    key: "hra_pri",
    label: "HRA PRI",
    src: "/tactical-markers/hra_pri.svg",
    group: "tactical",
  },
  {
    key: "hrp_alt",
    label: "HRP ALT",
    src: "/tactical-markers/hrp_alt.svg",
    group: "tactical",
  },
  {
    key: "hrp_pri",
    label: "HRP PRI",
    src: "/tactical-markers/hrp_pri.svg",
    group: "tactical",
  },
  {
    key: "indicator",
    label: "Indicator",
    src: "/tactical-markers/indicator.svg",
    group: "tactical",
  },
  {
    key: "inner_cordon",
    label: "Inner Cordon",
    src: "/tactical-markers/inner_cordon.svg",
    group: "tactical",
  },
  {
    key: "landslide_rv",
    label: "Landslide RV",
    src: "/tactical-markers/landslide_rv.svg",
    group: "tactical",
  },
  {
    key: "lay_up_point",
    label: "Lay Up Point",
    src: "/tactical-markers/lay_up_point.svg",
    group: "tactical",
  },
  {
    key: "lbs_1",
    label: "LBS_1",
    src: "/tactical-markers/lbs_1.svg",
    group: "tactical",
  },
  {
    key: "lbs_10",
    label: "LBS_10",
    src: "/tactical-markers/lbs_10.svg",
    group: "tactical",
  },
  {
    key: "lbs_11",
    label: "LBS_11",
    src: "/tactical-markers/lbs_11.svg",
    group: "tactical",
  },
  {
    key: "lbs_12",
    label: "LBS_12",
    src: "/tactical-markers/lbs_12.svg",
    group: "tactical",
  },
  {
    key: "lbs_2",
    label: "LBS_2",
    src: "/tactical-markers/lbs_2.svg",
    group: "tactical",
  },
  {
    key: "lbs_3",
    label: "LBS_3",
    src: "/tactical-markers/lbs_3.svg",
    group: "tactical",
  },
  {
    key: "lbs_4",
    label: "LBS_4",
    src: "/tactical-markers/lbs_4.svg",
    group: "tactical",
  },
  {
    key: "lbs_5",
    label: "LBS_5",
    src: "/tactical-markers/lbs_5.svg",
    group: "tactical",
  },
  {
    key: "lbs_6",
    label: "LBS_6",
    src: "/tactical-markers/lbs_6.svg",
    group: "tactical",
  },
  {
    key: "lbs_7",
    label: "LBS_7",
    src: "/tactical-markers/lbs_7.svg",
    group: "tactical",
  },
  {
    key: "lbs_8",
    label: "LBS_8",
    src: "/tactical-markers/lbs_8.svg",
    group: "tactical",
  },
  {
    key: "lbs_9",
    label: "LBS_9",
    src: "/tactical-markers/lbs_9.svg",
    group: "tactical",
  },
  {
    key: "marksman",
    label: "Marksman",
    src: "/tactical-markers/marksman.svg",
    group: "tactical",
  },
  {
    key: "marksman_1",
    label: "Marksman 1",
    src: "/tactical-markers/marksman_1.svg",
    group: "tactical",
  },
  {
    key: "marksman_2",
    label: "Marksman 2",
    src: "/tactical-markers/marksman_2.svg",
    group: "tactical",
  },
  {
    key: "marksman_3",
    label: "Marksman 3",
    src: "/tactical-markers/marksman_3.svg",
    group: "tactical",
  },
  {
    key: "marksman_4",
    label: "Marksman 4",
    src: "/tactical-markers/marksman_4.svg",
    group: "tactical",
  },
  {
    key: "marksman_5",
    label: "Marksman 5",
    src: "/tactical-markers/marksman_5.svg",
    group: "tactical",
  },
  {
    key: "marksman_6",
    label: "Marksman 6",
    src: "/tactical-markers/marksman_6.svg",
    group: "tactical",
  },
  {
    key: "marksman_7",
    label: "Marksman 7",
    src: "/tactical-markers/marksman_7.svg",
    group: "tactical",
  },
  {
    key: "marksman_8",
    label: "Marksman 8",
    src: "/tactical-markers/marksman_8.svg",
    group: "tactical",
  },
  {
    key: "marksman_9",
    label: "Marksman 9",
    src: "/tactical-markers/marksman_9.svg",
    group: "tactical",
  },
  {
    key: "media",
    label: "MEDIA",
    src: "/tactical-markers/media.svg",
    group: "personnel",
  },
  {
    key: "mobile_police_facility",
    label: "Mobile Police Facility",
    src: "/tactical-markers/mobile_police_facility.svg",
    group: "vehicles",
  },
  {
    key: "neg",
    label: "NEG",
    src: "/tactical-markers/neg.svg",
    group: "personnel",
  },
  {
    key: "negotiators",
    label: "Negotiators",
    src: "/tactical-markers/negotiators.svg",
    group: "personnel",
  },
  {
    key: "north",
    label: "NORTH",
    src: "/tactical-markers/north.svg",
    group: "tactical",
  },
  {
    key: "observation_point",
    label: "Observation Point",
    src: "/tactical-markers/observation_point.svg",
    group: "tactical",
  },
  {
    key: "occ",
    label: "OCC",
    src: "/tactical-markers/occ.svg",
    group: "tactical",
  },
  {
    key: "op",
    label: "OP",
    src: "/tactical-markers/op.svg",
    group: "tactical",
  },
  {
    key: "outer_cordon",
    label: "Outer Cordon",
    src: "/tactical-markers/outer_cordon.svg",
    group: "tactical",
  },
  {
    key: "oval_green",
    label: "Oval Green",
    src: "/tactical-markers/oval_green.svg",
    group: "tactical",
  },
  {
    key: "oval_green_screen",
    label: "Oval Green Screen",
    src: "/tactical-markers/oval_green_screen.svg",
    group: "tactical",
  },
  {
    key: "oval_red",
    label: "Oval Red",
    src: "/tactical-markers/oval_red.svg",
    group: "tactical",
  },
  {
    key: "pb",
    label: "PB",
    src: "/tactical-markers/pb.svg",
    group: "tactical",
  },
  {
    key: "petrol_station",
    label: "Petrol Station",
    src: "/tactical-markers/petrol_station.svg",
    group: "facilities",
  },
  {
    key: "police",
    label: "Police",
    src: "/tactical-markers/police.svg",
    group: "vehicles",
  },
  {
    key: "police_bike",
    label: "Police Bike",
    src: "/tactical-markers/police_bike.svg",
    group: "vehicles",
  },
  {
    key: "police_car",
    label: "Police Car",
    src: "/tactical-markers/police_car.svg",
    group: "vehicles",
  },
  {
    key: "police_forward_command_post",
    label: "Police Forward Command Post",
    src: "/tactical-markers/police_forward_command_post.svg",
    group: "tactical",
  },
  {
    key: "police_station",
    label: "Police Station",
    src: "/tactical-markers/police_station.svg",
    group: "facilities",
  },
  {
    key: "prop_car",
    label: "Prop Car",
    src: "/tactical-markers/prop_car.svg",
    group: "vehicles",
  },
  {
    key: "red_4wd",
    label: "RED 4WD",
    src: "/tactical-markers/red_4wd.svg",
    group: "vehicles",
  },
  {
    key: "red_cutoff",
    label: "RED CUTOFF",
    src: "/tactical-markers/red_cutoff.svg",
    group: "tactical",
  },
  {
    key: "red_side",
    label: "RED SIDE",
    src: "/tactical-markers/red_side.svg",
    group: "tactical",
  },
  {
    key: "rendezvous_point",
    label: "Rendezvous Point",
    src: "/tactical-markers/rendezvous_point.svg",
    group: "tactical",
  },
  {
    key: "repeater",
    label: "Repeater",
    src: "/tactical-markers/repeater.svg",
    group: "tactical",
  },
  {
    key: "rv",
    label: "RV",
    src: "/tactical-markers/rv.svg",
    group: "tactical",
  },
  {
    key: "sa",
    label: "SA",
    src: "/tactical-markers/sa.svg",
    group: "tactical",
  },
  {
    key: "school",
    label: "School",
    src: "/tactical-markers/school.svg",
    group: "facilities",
  },
  {
    key: "sh",
    label: "SH",
    src: "/tactical-markers/sh.svg",
    group: "tactical",
  },
  {
    key: "sh1",
    label: "SH1",
    src: "/tactical-markers/sh1.svg",
    group: "tactical",
  },
  {
    key: "sh2",
    label: "SH2",
    src: "/tactical-markers/sh2.svg",
    group: "tactical",
  },
  {
    key: "sh3",
    label: "SH3",
    src: "/tactical-markers/sh3.svg",
    group: "tactical",
  },
  {
    key: "sh4",
    label: "SH4",
    src: "/tactical-markers/sh4.svg",
    group: "tactical",
  },
  {
    key: "sh5",
    label: "SH5",
    src: "/tactical-markers/sh5.svg",
    group: "tactical",
  },
  {
    key: "sh6",
    label: "SH6",
    src: "/tactical-markers/sh6.svg",
    group: "tactical",
  },
  {
    key: "sh7",
    label: "SH7",
    src: "/tactical-markers/sh7.svg",
    group: "tactical",
  },
  {
    key: "sh8",
    label: "SH8",
    src: "/tactical-markers/sh8.svg",
    group: "tactical",
  },
  {
    key: "sh9",
    label: "SH9",
    src: "/tactical-markers/sh9.svg",
    group: "tactical",
  },
  {
    key: "shopping_centre",
    label: "Shopping Centre",
    src: "/tactical-markers/shopping_centre.svg",
    group: "facilities",
  },
  {
    key: "sierra1",
    label: "SIERRA1",
    src: "/tactical-markers/sierra1.svg",
    group: "tactical",
  },
  {
    key: "sierra2",
    label: "SIERRA2",
    src: "/tactical-markers/sierra2.svg",
    group: "tactical",
  },
  {
    key: "sierra3",
    label: "SIERRA3",
    src: "/tactical-markers/sierra3.svg",
    group: "tactical",
  },
  {
    key: "sierra4",
    label: "SIERRA4",
    src: "/tactical-markers/sierra4.svg",
    group: "tactical",
  },
  {
    key: "sierra5",
    label: "SIERRA5",
    src: "/tactical-markers/sierra5.svg",
    group: "tactical",
  },
  {
    key: "silver_4wd",
    label: "SILVER 4WD",
    src: "/tactical-markers/silver_4wd.svg",
    group: "vehicles",
  },
  {
    key: "south",
    label: "SOUTH",
    src: "/tactical-markers/south.svg",
    group: "tactical",
  },
  {
    key: "split_holding_area",
    label: "Split Holding Area",
    src: "/tactical-markers/split_holding_area.svg",
    group: "tactical",
  },
  {
    key: "srp",
    label: "SRP",
    src: "/tactical-markers/srp.svg",
    group: "tactical",
  },
  {
    key: "stand_to_loc",
    label: "Stand To Loc",
    src: "/tactical-markers/stand_to_loc.svg",
    group: "tactical",
  },
  {
    key: "standto",
    label: "STANDTO",
    src: "/tactical-markers/standto.svg",
    group: "tactical",
  },
  {
    key: "state_emergency_service",
    label: "State Emergency Service",
    src: "/tactical-markers/state_emergency_service.svg",
    group: "tactical",
  },
  {
    key: "stingers",
    label: "Stingers",
    src: "/tactical-markers/stingers.svg",
    group: "tactical",
  },
  {
    key: "stronghold",
    label: "Stronghold",
    src: "/tactical-markers/stronghold.svg",
    group: "tactical",
  },
  {
    key: "stronghold_1",
    label: "Stronghold 1",
    src: "/tactical-markers/stronghold_1.svg",
    group: "tactical",
  },
  {
    key: "stronghold_10",
    label: "Stronghold 10",
    src: "/tactical-markers/stronghold_10.svg",
    group: "tactical",
  },
  {
    key: "stronghold_11",
    label: "Stronghold 11",
    src: "/tactical-markers/stronghold_11.svg",
    group: "tactical",
  },
  {
    key: "stronghold_12",
    label: "Stronghold 12",
    src: "/tactical-markers/stronghold_12.svg",
    group: "tactical",
  },
  {
    key: "stronghold_13",
    label: "Stronghold 13",
    src: "/tactical-markers/stronghold_13.svg",
    group: "tactical",
  },
  {
    key: "stronghold_14",
    label: "Stronghold 14",
    src: "/tactical-markers/stronghold_14.svg",
    group: "tactical",
  },
  {
    key: "stronghold_15",
    label: "Stronghold 15",
    src: "/tactical-markers/stronghold_15.svg",
    group: "tactical",
  },
  {
    key: "stronghold_16",
    label: "Stronghold 16",
    src: "/tactical-markers/stronghold_16.svg",
    group: "tactical",
  },
  {
    key: "stronghold_17",
    label: "Stronghold 17",
    src: "/tactical-markers/stronghold_17.svg",
    group: "tactical",
  },
  {
    key: "stronghold_18",
    label: "Stronghold 18",
    src: "/tactical-markers/stronghold_18.svg",
    group: "tactical",
  },
  {
    key: "stronghold_19",
    label: "Stronghold 19",
    src: "/tactical-markers/stronghold_19.svg",
    group: "tactical",
  },
  {
    key: "stronghold_2",
    label: "Stronghold 2",
    src: "/tactical-markers/stronghold_2.svg",
    group: "tactical",
  },
  {
    key: "stronghold_20",
    label: "Stronghold 20",
    src: "/tactical-markers/stronghold_20.svg",
    group: "tactical",
  },
  {
    key: "stronghold_21",
    label: "Stronghold 21",
    src: "/tactical-markers/stronghold_21.svg",
    group: "tactical",
  },
  {
    key: "stronghold_22",
    label: "Stronghold 22",
    src: "/tactical-markers/stronghold_22.svg",
    group: "tactical",
  },
  {
    key: "stronghold_23",
    label: "Stronghold 23",
    src: "/tactical-markers/stronghold_23.svg",
    group: "tactical",
  },
  {
    key: "stronghold_24",
    label: "Stronghold 24",
    src: "/tactical-markers/stronghold_24.svg",
    group: "tactical",
  },
  {
    key: "stronghold_25",
    label: "Stronghold 25",
    src: "/tactical-markers/stronghold_25.svg",
    group: "tactical",
  },
  {
    key: "stronghold_26",
    label: "Stronghold 26",
    src: "/tactical-markers/stronghold_26.svg",
    group: "tactical",
  },
  {
    key: "stronghold_27",
    label: "Stronghold 27",
    src: "/tactical-markers/stronghold_27.svg",
    group: "tactical",
  },
  {
    key: "stronghold_28",
    label: "Stronghold 28",
    src: "/tactical-markers/stronghold_28.svg",
    group: "tactical",
  },
  {
    key: "stronghold_29",
    label: "Stronghold 29",
    src: "/tactical-markers/stronghold_29.svg",
    group: "tactical",
  },
  {
    key: "stronghold_3",
    label: "Stronghold 3",
    src: "/tactical-markers/stronghold_3.svg",
    group: "tactical",
  },
  {
    key: "stronghold_30",
    label: "Stronghold 30",
    src: "/tactical-markers/stronghold_30.svg",
    group: "tactical",
  },
  {
    key: "stronghold_31",
    label: "Stronghold 31",
    src: "/tactical-markers/stronghold_31.svg",
    group: "tactical",
  },
  {
    key: "stronghold_4",
    label: "Stronghold 4",
    src: "/tactical-markers/stronghold_4.svg",
    group: "tactical",
  },
  {
    key: "stronghold_5",
    label: "Stronghold 5",
    src: "/tactical-markers/stronghold_5.svg",
    group: "tactical",
  },
  {
    key: "stronghold_6",
    label: "Stronghold 6",
    src: "/tactical-markers/stronghold_6.svg",
    group: "tactical",
  },
  {
    key: "stronghold_7",
    label: "Stronghold 7",
    src: "/tactical-markers/stronghold_7.svg",
    group: "tactical",
  },
  {
    key: "stronghold_8",
    label: "Stronghold 8",
    src: "/tactical-markers/stronghold_8.svg",
    group: "tactical",
  },
  {
    key: "stronghold_9",
    label: "Stronghold 9",
    src: "/tactical-markers/stronghold_9.svg",
    group: "tactical",
  },
  {
    key: "subject_address",
    label: "Subject Address",
    src: "/tactical-markers/subject_address.svg",
    group: "target_associates",
  },
  {
    key: "subject_vehicle",
    label: "Subject Vehicle",
    src: "/tactical-markers/subject_vehicle.svg",
    group: "target_associates",
  },
  {
    key: "surv",
    label: "SURV",
    src: "/tactical-markers/surv.svg",
    group: "tactical",
  },
  {
    key: "surveillance_foot_team",
    label: "Surveillance Foot Team",
    src: "/tactical-markers/surveillance_foot_team.svg",
    group: "tactical",
  },
  {
    key: "surveillance_vehicle",
    label: "Surveillance Vehicle",
    src: "/tactical-markers/surveillance_vehicle.svg",
    group: "tactical",
  },
  {
    key: "tactical_command_post",
    label: "Tactical Command Post",
    src: "/tactical-markers/tactical_command_post.svg",
    group: "tactical",
  },
  {
    key: "tango",
    label: "Tango",
    src: "/tactical-markers/tango.svg",
    group: "tactical",
  },
  {
    key: "technical_surveillance_unit",
    label: "Technical Surveillance Unit",
    src: "/tactical-markers/technical_surveillance_unit.svg",
    group: "tactical",
  },
  {
    key: "terr",
    label: "TERR",
    src: "/tactical-markers/terr.svg",
    group: "tactical",
  },
  {
    key: "toilets",
    label: "Toilets",
    src: "/tactical-markers/toilets.svg",
    group: "facilities",
  },
  {
    key: "trip_wire",
    label: "Trip Wire",
    src: "/tactical-markers/trip_wire.svg",
    group: "tactical",
  },
  {
    key: "tsu",
    label: "TSU",
    src: "/tactical-markers/tsu.svg",
    group: "tactical",
  },
  {
    key: "vehicle_approach",
    label: "Vehicle Approach",
    src: "/tactical-markers/vehicle_approach.svg",
    group: "tactical",
  },
  {
    key: "vehicle_approach_alpha",
    label: "Vehicle Approach Alpha",
    src: "/tactical-markers/vehicle_approach_alpha.svg",
    group: "tactical",
  },
  {
    key: "vehicle_approach_bravo",
    label: "Vehicle Approach Bravo",
    src: "/tactical-markers/vehicle_approach_bravo.svg",
    group: "tactical",
  },
  {
    key: "vehicle_approach_charlie",
    label: "Vehicle Approach Charlie",
    src: "/tactical-markers/vehicle_approach_charlie.svg",
    group: "tactical",
  },
  {
    key: "vehicle_approach_delta",
    label: "Vehicle Approach Delta",
    src: "/tactical-markers/vehicle_approach_delta.svg",
    group: "tactical",
  },
  {
    key: "vehicle_approach_echo",
    label: "Vehicle Approach Echo",
    src: "/tactical-markers/vehicle_approach_echo.svg",
    group: "tactical",
  },
  {
    key: "vehicle_approach_golf",
    label: "Vehicle Approach Golf",
    src: "/tactical-markers/vehicle_approach_golf.svg",
    group: "tactical",
  },
  {
    key: "vehicle_approach_marksman",
    label: "Vehicle Approach Marksman",
    src: "/tactical-markers/vehicle_approach_marksman.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point",
    label: "Vehicle Stop Point",
    src: "/tactical-markers/vehicle_stop_point.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_1",
    label: "Vehicle Stop Point 1",
    src: "/tactical-markers/vehicle_stop_point_1.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_2",
    label: "Vehicle Stop Point 2",
    src: "/tactical-markers/vehicle_stop_point_2.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_all_teams",
    label: "Vehicle Stop Point All Teams",
    src: "/tactical-markers/vehicle_stop_point_all_teams.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_alpha",
    label: "Vehicle Stop Point Alpha",
    src: "/tactical-markers/vehicle_stop_point_alpha.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_alpha_1",
    label: "Vehicle Stop Point Alpha 1",
    src: "/tactical-markers/vehicle_stop_point_alpha_1.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_alpha_2",
    label: "Vehicle Stop Point Alpha 2",
    src: "/tactical-markers/vehicle_stop_point_alpha_2.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_bravo",
    label: "Vehicle Stop Point Bravo",
    src: "/tactical-markers/vehicle_stop_point_bravo.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_bravo_1",
    label: "Vehicle Stop Point Bravo 1",
    src: "/tactical-markers/vehicle_stop_point_bravo_1.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_bravo_2",
    label: "Vehicle Stop Point Bravo 2",
    src: "/tactical-markers/vehicle_stop_point_bravo_2.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_charlie",
    label: "Vehicle Stop Point Charlie",
    src: "/tactical-markers/vehicle_stop_point_charlie.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_charlie_1",
    label: "Vehicle Stop Point Charlie 1",
    src: "/tactical-markers/vehicle_stop_point_charlie_1.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_charlie_2",
    label: "Vehicle Stop Point Charlie 2",
    src: "/tactical-markers/vehicle_stop_point_charlie_2.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_delta",
    label: "Vehicle Stop Point Delta",
    src: "/tactical-markers/vehicle_stop_point_delta.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_delta_1",
    label: "Vehicle Stop Point Delta 1",
    src: "/tactical-markers/vehicle_stop_point_delta_1.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_delta_2",
    label: "Vehicle Stop Point Delta 2",
    src: "/tactical-markers/vehicle_stop_point_delta_2.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_golf",
    label: "Vehicle Stop Point Golf",
    src: "/tactical-markers/vehicle_stop_point_golf.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_golf_1",
    label: "Vehicle Stop Point Golf 1",
    src: "/tactical-markers/vehicle_stop_point_golf_1.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_golf_2",
    label: "Vehicle Stop Point Golf 2",
    src: "/tactical-markers/vehicle_stop_point_golf_2.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_marksman",
    label: "Vehicle Stop Point Marksman",
    src: "/tactical-markers/vehicle_stop_point_marksman.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_marksman_1",
    label: "Vehicle Stop Point Marksman 1",
    src: "/tactical-markers/vehicle_stop_point_marksman_1.svg",
    group: "tactical",
  },
  {
    key: "vehicle_stop_point_marksman_2",
    label: "Vehicle Stop Point Marksman 2",
    src: "/tactical-markers/vehicle_stop_point_marksman_2.svg",
    group: "tactical",
  },
  {
    key: "vehicle_team_1",
    label: "Vehicle Team 1",
    src: "/tactical-markers/vehicle_team_1.svg",
    group: "tactical",
  },
  {
    key: "vehicle_team_2",
    label: "Vehicle Team 2",
    src: "/tactical-markers/vehicle_team_2.svg",
    group: "tactical",
  },
  {
    key: "vehicle_team_3",
    label: "Vehicle Team 3",
    src: "/tactical-markers/vehicle_team_3.svg",
    group: "tactical",
  },
  {
    key: "vehicle_team_4",
    label: "Vehicle Team 4",
    src: "/tactical-markers/vehicle_team_4.svg",
    group: "tactical",
  },
  {
    key: "vehicle_team_5",
    label: "Vehicle Team 5",
    src: "/tactical-markers/vehicle_team_5.svg",
    group: "tactical",
  },
  {
    key: "vehicle_team_6",
    label: "Vehicle Team 6",
    src: "/tactical-markers/vehicle_team_6.svg",
    group: "tactical",
  },
  {
    key: "vehicle_team_7",
    label: "Vehicle Team 7",
    src: "/tactical-markers/vehicle_team_7.svg",
    group: "tactical",
  },
  {
    key: "vehicle_team_8",
    label: "Vehicle Team 8",
    src: "/tactical-markers/vehicle_team_8.svg",
    group: "tactical",
  },
  {
    key: "vehicle_team_9",
    label: "Vehicle Team 9",
    src: "/tactical-markers/vehicle_team_9.svg",
    group: "tactical",
  },
  {
    key: "vehstp",
    label: "VEHSTP",
    src: "/tactical-markers/vehstp.svg",
    group: "tactical",
  },
  {
    key: "vehstp_1",
    label: "VEHSTP-1",
    src: "/tactical-markers/vehstp_1.svg",
    group: "tactical",
  },
  {
    key: "vehstp_2",
    label: "VEHSTP-2",
    src: "/tactical-markers/vehstp_2.svg",
    group: "tactical",
  },
  {
    key: "vehstp_a",
    label: "VEHSTP-A",
    src: "/tactical-markers/vehstp_a.svg",
    group: "tactical",
  },
  {
    key: "vehstp_a1",
    label: "VEHSTP-A1",
    src: "/tactical-markers/vehstp_a1.svg",
    group: "tactical",
  },
  {
    key: "vehstp_a2",
    label: "VEHSTP-A2",
    src: "/tactical-markers/vehstp_a2.svg",
    group: "tactical",
  },
  {
    key: "vehstp_b",
    label: "VEHSTP-B",
    src: "/tactical-markers/vehstp_b.svg",
    group: "tactical",
  },
  {
    key: "vehstp_b1",
    label: "VEHSTP-B1",
    src: "/tactical-markers/vehstp_b1.svg",
    group: "tactical",
  },
  {
    key: "vehstp_b2",
    label: "VEHSTP-B2",
    src: "/tactical-markers/vehstp_b2.svg",
    group: "tactical",
  },
  {
    key: "vehstp_c",
    label: "VEHSTP-C",
    src: "/tactical-markers/vehstp_c.svg",
    group: "tactical",
  },
  {
    key: "vehstp_c1",
    label: "VEHSTP-C1",
    src: "/tactical-markers/vehstp_c1.svg",
    group: "tactical",
  },
  {
    key: "vehstp_c2",
    label: "VEHSTP-C2",
    src: "/tactical-markers/vehstp_c2.svg",
    group: "tactical",
  },
  {
    key: "vehstp_d",
    label: "VEHSTP-D",
    src: "/tactical-markers/vehstp_d.svg",
    group: "tactical",
  },
  {
    key: "vehstp_d1",
    label: "VEHSTP-D1",
    src: "/tactical-markers/vehstp_d1.svg",
    group: "tactical",
  },
  {
    key: "vehstp_d2",
    label: "VEHSTP-D2",
    src: "/tactical-markers/vehstp_d2.svg",
    group: "tactical",
  },
  {
    key: "very_important_person",
    label: "Very Important Person",
    src: "/tactical-markers/very_important_person.svg",
    group: "personnel",
  },
  {
    key: "vessell",
    label: "Vessell",
    src: "/tactical-markers/vessell.svg",
    group: "vehicles",
  },
  {
    key: "vip",
    label: "VIP",
    src: "/tactical-markers/vip.svg",
    group: "personnel",
  },
  {
    key: "voi_1",
    label: "VOI 1",
    src: "/tactical-markers/voi_1.svg",
    group: "personnel",
  },
  {
    key: "voi_2",
    label: "VOI 2",
    src: "/tactical-markers/voi_2.svg",
    group: "personnel",
  },
  {
    key: "voi_3",
    label: "VOI 3",
    src: "/tactical-markers/voi_3.svg",
    group: "personnel",
  },
  {
    key: "voi_4",
    label: "VOI 4",
    src: "/tactical-markers/voi_4.svg",
    group: "personnel",
  },
  {
    key: "voi_5",
    label: "VOI 5",
    src: "/tactical-markers/voi_5.svg",
    group: "personnel",
  },
  {
    key: "voi_6",
    label: "VOI 6",
    src: "/tactical-markers/voi_6.svg",
    group: "personnel",
  },
  {
    key: "west",
    label: "WEST",
    src: "/tactical-markers/west.svg",
    group: "tactical",
  },
  {
    key: "white_cutoff",
    label: "WHITE CUTOFF",
    src: "/tactical-markers/white_cutoff.svg",
    group: "tactical",
  },
  {
    key: "white_side",
    label: "White Side",
    src: "/tactical-markers/white_side.svg",
    group: "tactical",
  },
  {
    key: "x_circle",
    label: "X+Circle",
    src: "/tactical-markers/x_circle.svg",
    group: "tactical",
  },
];
export const TACTICAL_ICONS_BY_GROUP: Record<TacticalGroup, TacticalIcon[]> =
  TACTICAL_GROUPS.reduce(
    (acc, g) => {
      acc[g.key] = TACTICAL_ICONS.filter(t => t.group === g.key);
      return acc;
    },
    {} as Record<TacticalGroup, TacticalIcon[]>
  );

const TACTICAL_ICON_MAP: Record<string, TacticalIcon> = Object.fromEntries(
  TACTICAL_ICONS.map(t => [t.key, t])
);

export function isTacticalIcon(icon: string): boolean {
  return icon in TACTICAL_ICON_MAP;
}

export function getTacticalIconSrc(icon: string): string | null {
  return TACTICAL_ICON_MAP[icon]?.src ?? null;
}

export function getTacticalIconLabel(icon: string): string | null {
  return TACTICAL_ICON_MAP[icon]?.label ?? null;
}
