CREATE TABLE `sheet_summaries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sheetId` int NOT NULL,
	`teamLabel` varchar(100),
	`teamCins` text,
	`operationName` varchar(255),
	`dayDate` varchar(64),
	`startTime` varchar(32),
	`finishTime` varchar(32),
	`targetName` text,
	`address` text,
	`ioSupport` text,
	`intelSupport` text,
	`specialProjects` text,
	`objectives` text,
	`criticalDecisions` text,
	`summary` text,
	`newIntelForProfile` text,
	`issues` text,
	`lastEditedByCIN` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sheet_summaries_id` PRIMARY KEY(`id`),
	CONSTRAINT `sheet_summaries_sheetId_unique` UNIQUE(`sheetId`)
);
