CREATE TABLE `cameras` (
	`id` int AUTO_INCREMENT NOT NULL,
	`connectorId` int NOT NULL,
	`operationId` int,
	`externalCameraId` varchar(255),
	`name` varchar(255) NOT NULL,
	`manufacturer` varchar(255),
	`model` varchar(255),
	`locationName` varchar(255),
	`latitude` double,
	`longitude` double,
	`description` text,
	`mediaPath` varchar(255),
	`rtspSourceRef` text,
	`webRtcUrl` varchar(500),
	`hlsUrl` varchar(500),
	`status` enum('ONLINE','OFFLINE','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
	`lastSeen` bigint,
	`enabled` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` bigint,
	`deletedByCIN` varchar(64),
	CONSTRAINT `cameras_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `connector_audit_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`connectorId` int,
	`userId` int NOT NULL,
	`userCIN` varchar(64),
	`action` varchar(64) NOT NULL,
	`detail` varchar(512),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `connector_audit_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `connectors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`connectorType` enum('CAMERA','GPS','SIGNAL','SENSOR','VMS','OTHER') NOT NULL,
	`provider` varchar(255) NOT NULL,
	`description` text,
	`enabled` boolean NOT NULL DEFAULT true,
	`connectionStatus` enum('CONNECTED','DISCONNECTED','CONNECTING','ERROR','DISABLED') NOT NULL DEFAULT 'DISCONNECTED',
	`healthStatus` enum('HEALTHY','DEGRADED','OFFLINE','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
	`lastConnectedAt` bigint,
	`lastDataReceivedAt` bigint,
	`operationId` int,
	`configuration` text,
	`credentialsRef` text,
	`createdBy` int NOT NULL,
	`createdByCIN` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` bigint,
	`deletedByCIN` varchar(64),
	CONSTRAINT `connectors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `external_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`operationId` int,
	`connectorId` int NOT NULL,
	`sourceType` enum('CAMERA','GPS','SIGNAL','SENSOR','VMS','OTHER') NOT NULL,
	`sourceProvider` varchar(255),
	`sourceDeviceId` varchar(255),
	`eventType` varchar(64) NOT NULL,
	`eventTime` bigint NOT NULL,
	`receivedTime` bigint NOT NULL,
	`latitude` double,
	`longitude` double,
	`altitude` double,
	`heading` double,
	`speed` double,
	`accuracy` double,
	`title` varchar(255),
	`description` text,
	`entityType` varchar(64),
	`entityId` int,
	`confidence` int,
	`severity` varchar(32),
	`metadataJson` text,
	`rawEventReference` text,
	`isSimulated` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `external_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `signal_detections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`operationId` int,
	`connectorId` int NOT NULL,
	`sensorId` int NOT NULL,
	`externalDeviceReference` varchar(255) NOT NULL,
	`signalType` varchar(32) NOT NULL,
	`latitude` double,
	`longitude` double,
	`confidence` int,
	`signalStrength` int,
	`firstDetectedAt` bigint NOT NULL,
	`lastDetectedAt` bigint NOT NULL,
	`direction` varchar(32),
	`status` enum('ACTIVE','LOST') NOT NULL DEFAULT 'ACTIVE',
	`associatedEntityId` int,
	`metadataJson` text,
	`isSimulated` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `signal_detections_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `signal_sensors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`connectorId` int NOT NULL,
	`operationId` int,
	`externalSensorId` varchar(255),
	`name` varchar(255) NOT NULL,
	`sensorType` varchar(32),
	`latitude` double,
	`longitude` double,
	`locationName` varchar(255),
	`status` enum('ONLINE','OFFLINE','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
	`lastSeen` bigint,
	`metadataJson` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` bigint,
	`deletedByCIN` varchar(64),
	CONSTRAINT `signal_sensors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tracked_asset_positions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`trackedAssetId` int NOT NULL,
	`operationId` int,
	`latitude` double NOT NULL,
	`longitude` double NOT NULL,
	`altitude` double,
	`speed` double,
	`heading` double,
	`accuracy` double,
	`recordedAt` bigint NOT NULL,
	CONSTRAINT `tracked_asset_positions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tracked_assets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`operationId` int,
	`connectorId` int NOT NULL,
	`externalDeviceId` varchar(255),
	`name` varchar(255) NOT NULL,
	`assetType` enum('VEHICLE','MEMBER','DEVICE','EQUIPMENT','TARGET','OTHER') NOT NULL,
	`assignedEntityId` int,
	`assignedVehicleId` int,
	`assignedMemberId` int,
	`latitude` double,
	`longitude` double,
	`altitude` double,
	`speed` double,
	`heading` double,
	`accuracy` double,
	`batteryLevel` int,
	`ignitionStatus` varchar(16),
	`onlineStatus` enum('ONLINE','OFFLINE','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
	`lastPositionTime` bigint,
	`lastReceivedTime` bigint,
	`simulatedWaypoints` text,
	`simulatedLoopSeconds` int,
	`metadataJson` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` bigint,
	`deletedByCIN` varchar(64),
	CONSTRAINT `tracked_assets_id` PRIMARY KEY(`id`)
);
