CREATE TABLE `uco_guide_acknowledgements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`briefingId` int NOT NULL,
	`userId` int NOT NULL,
	`cin` varchar(64) NOT NULL,
	`revision` int NOT NULL DEFAULT 1,
	`acknowledgedAt` bigint NOT NULL,
	CONSTRAINT `uco_guide_acknowledgements_id` PRIMARY KEY(`id`),
	CONSTRAINT `uco_guide_ack_briefing_user_rev_idx` UNIQUE(`briefingId`,`userId`,`revision`)
);
--> statement-breakpoint
CREATE TABLE `uco_guide_briefings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`operationId` int NOT NULL,
	`sheetId` int,
	`targetId` int,
	`accoutrements` text,
	`moeEquipment` text,
	`opBackground` text,
	`opObjective` text,
	`riskAssessment` text,
	`ucoPhotoRef` varchar(500),
	`ucoVehiclePhotoRef` varchar(500),
	`ucoNames` varchar(255),
	`planObjective` varchar(500),
	`planTimings` varchar(255),
	`planControllerLocation` varchar(255),
	`planTracking` varchar(255),
	`planComms` varchar(255),
	`planDangerSignal` varchar(255),
	`planIngressEgress` text,
	`planAuthorisedActions` text,
	`teamLeaderCin` varchar(64),
	`seniorOperativeCin` varchar(64),
	`huxCin` varchar(64),
	`ramCin` varchar(64),
	`additionalMemberCins` text,
	`tacticsNotes` text,
	`currentLevel` int NOT NULL DEFAULT 2,
	`levelNotes` text,
	`commsVehiclePrimary` varchar(255),
	`commsVehicleAlternate` varchar(255),
	`commsFootPrimary` varchar(255),
	`commsFootAlternate` varchar(255),
	`commsNotes` text,
	`recipientCins` text,
	`status` enum('draft','posted') NOT NULL DEFAULT 'draft',
	`revision` int NOT NULL DEFAULT 1,
	`postedAt` bigint,
	`postedByCIN` varchar(64),
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` bigint,
	`deletedByCIN` varchar(64),
	CONSTRAINT `uco_guide_briefings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `audit_logs` MODIFY COLUMN `action` enum('row_created','row_updated','row_deleted','member_added','member_removed','certified','uncertified','sheet_created','sheet_updated','sheet_deleted','sheet_closed','sheet_reopened','sheet_moved','sheet_copied','user_login','user_logout','user_created','user_updated','user_deleted','operation_status_changed','password_changed','attachment_added','attachment_deleted','summary_completed','summary_reopened','smeac_briefing_posted','smeac_briefing_deleted','uco_guide_posted','uco_guide_deleted') NOT NULL;
