CREATE TABLE `map_shapes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`createdBy` int NOT NULL,
	`operationId` int,
	`shapeType` enum('circle','rectangle','sector','line') NOT NULL,
	`colour` varchar(32) NOT NULL,
	`opacity` int NOT NULL DEFAULT 30,
	`label` varchar(255),
	`centerLat` double,
	`centerLng` double,
	`radiusMeters` double,
	`startAngle` double,
	`endAngle` double,
	`neLat` double,
	`neLng` double,
	`swLat` double,
	`swLng` double,
	`points` text,
	`deletedAt` bigint,
	`deletedByCIN` varchar(32),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `map_shapes_id` PRIMARY KEY(`id`)
);
